name: _node-setup
description: Checkout repository, setup Node.js and install dependencies

inputs:
  node_version:
    description: "Node.js version"
    required: false
    default: "20"

  workdir:
    description: "Working directory"
    required: false
    default: "."

  registry_url:
    description: "Optional npm registry URL"
    required: false
    default: ""

  scope:
    description: "Optional npm scope"
    required: false
    default: ""

  install_command:
    description: "Install command"
    required: false
    default: "npm ci --prefer-offline"

  fetch_depth:
    description: "Git fetch depth"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch_depth }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: npm
        cache-dependency-path: ${{ inputs.workdir }}/package-lock.json
        registry-url: ${{ inputs.registry_url }}
        scope: ${{ inputs.scope }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: ${{ inputs.install_command }}
